openapi: 3.0.3
info:
  title: Recipe Master API
  description: API for managing recipes with ingredients
  version: 1.0.0
  contact:
    name: Recipe Master API Team
servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /api/v1/recipes:
    get:
      tags:
        - Recipe Query
      summary: Get all recipes
      description: Retrieves a list of all recipes
      operationId: getAllRecipes
      responses:
        '200':
          description: Successfully retrieved recipes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RecipeDto'
        '500':
          description: Internal server error
    post:
      tags:
        - Recipe Command
      summary: Create a new recipe
      description: Creates a new recipe with ingredients
      operationId: createRecipe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeDto'
      responses:
        '201':
          description: Recipe created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'
        '400':
          description: Invalid input data
        '422':
          description: Validation error

  /api/v1/recipes/{id}:
    get:
      tags:
        - Recipe Query
      summary: Get recipe by ID
      description: Retrieves a specific recipe by its ID
      operationId: getRecipe
      parameters:
        - name: id
          in: path
          required: true
          description: Recipe ID
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Recipe found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'
        '404':
          description: Recipe not found
    put:
      tags:
        - Recipe Command
      summary: Update an existing recipe
      description: Updates a recipe by ID
      operationId: updateRecipe
      parameters:
        - name: id
          in: path
          required: true
          description: Recipe ID
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RecipeDto'
      responses:
        '200':
          description: Recipe updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RecipeDto'
        '400':
          description: Invalid input data
        '404':
          description: Recipe not found
    delete:
      tags:
        - Recipe Command
      summary: Delete an existing recipe
      description: Delete a recipe by ID
      operationId: deleteRecipe
      parameters:
        - name: id
          in: path
          required: true
          description: Recipe ID
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Recipe deleted successfully
        '404':
          description: Recipe not found

components:
  schemas:
    RecipeDto:
      type: object
      required:
        - name
        - instructions
        - servings
        - vegetarian
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the recipe
          readOnly: true
        name:
          type: string
          maxLength: 255
          description: Name of the recipe
          example: "Chocolate Chip Cookies"
        instructions:
          type: string
          description: Cooking instructions
          example: "Mix ingredients and bake for 15 minutes"
        servings:
          type: integer
          minimum: 1
          description: Number of servings
          example: 4
        vegetarian:
          type: boolean
          description: Whether the recipe is vegetarian
          example: true
        description:
          type: string
          maxLength: 1000
          description: Recipe description
          example: "Delicious homemade cookies"
        prepTimeMinutes:
          type: integer
          minimum: 0
          description: Preparation time in minutes
          example: 15
        cookTimeMinutes:
          type: integer
          minimum: 0
          description: Cooking time in minutes
          example: 30
        difficulty:
          type: string
          enum: [EASY, MEDIUM, HARD]
          description: Recipe difficulty level
          example: "EASY"
        ingredients:
          type: array
          items:
            $ref: '#/components/schemas/IngredientDto'
          description: List of ingredients
        createdAt:
          type: string
          format: date-time
          description: Recipe creation timestamp
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Recipe last update timestamp
          readOnly: true

    IngredientDto:
      type: object
      required:
        - name
        - quantity
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the ingredient
          readOnly: true
        name:
          type: string
          maxLength: 255
          description: Name of the ingredient
          example: "Flour"
        quantity:
          type: string
          maxLength: 100
          description: Quantity of the ingredient
          example: "2 cups"
        unit:
          type: string
          maxLength: 50
          description: Unit of measurement
          example: "cups"
